# Generated by Django 5.2.1 on 2025-05-30 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('description', models.TextField(verbose_name='설명')),
                ('real_estate_property_type', models.CharField(choices=[('APARTMENT', '아파트'), ('HOUSE', '주택'), ('COMMERCIAL', '상가'), ('OFFICE', '사무실')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='가격')),
                ('address', models.CharField(max_length=200, verbose_name='주소')),
                ('area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='면적')),
                ('rooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL, verbose_name='소유자')),
            ],
            options={
                'verbose_name': '부동산 매물',
                'verbose_name_plural': '부동산 매물',
                'ordering': ['-created_at'],
            },
        ),
    ]
